version: "3.9"

services:
  postgres:
    build: ./db
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: motorcycles
      POSTGRES_USER: user
      POSTGRES_PASSWORD: strongPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: strongPassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

  client:
    build: ./client
    container_name: web-app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app d
      - ./media:/app/public/media
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
